#gateway-service.yaml
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Tự động map service name thành route
          lower-case-service-id: true
      routes:
        - id: identity-service
          uri: lb://identity-service # lb = Load Balancer (qua Eureka)
          predicates:
            - Path=/api/v1/auth/**,/api/v1/users/**

        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/api/v1/posts/**
          filters:
            - AuthenticationFilter
management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
