server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://social_user:social_password@localhost:27017/social_post_db?authSource=admin
      # Lưu ý: database name là social_post_db

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/